[workspace]
members = [
    "crates/core",
    "crates/macros",
    "crates/cli",
]
resolver = "2"

[workspace.package]
name = "rustx-lang"
version = "0.2.0"
edition = "2021"
authors = ["Grandpa EJ <>"]
license = "MIT"
repository = "https://github.com/GrandpaEJx/RustX"
