[package]
name = "rustx"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "rustx"
path = "src/main.rs"

[[bin]]
name = "embed_demo"
path = "demo/embed_demo.rs"

[profile.release]
opt-level = 3
debug = false
strip = true
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
